name: Deploy DonutSMP Verification System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test application
      run: |
        python -m pytest --version || echo "No tests configured"
        python -c "import main; print('✅ Flask app imports successfully')"
        python -c "import bot; print('✅ Discord bot imports successfully')"
    
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying to Railway (configure webhook in Railway dashboard)"
        echo "Or connect this repo to Railway for automatic deployments"